gradle:
  image: gradle:4.5-alpine
  working_dir: /home/gradle/project
  volumes:
    - ./:/home/gradle/project
    - ~/.m2:/home/gradle/.m2
    - ~/.gradle:/home/gradle/.gradle

maven:
  image: maven:3.5-jdk-8-slim
  volumes:
    - ./:/usr/src
    - ~/.m2:/var/maven/.m2

node:
  image: opendigitaleducation/node:16-alpine
  working_dir: /home/node/app
  net: host
  volumes:
    - ./:/home/node/app
    - ~/.npm:/.npm
